[package]
name = "svod-schedule"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Optimization passes and pattern engine for the Svod ML compiler"
readme = "README.md"

[dependencies]
svod-ir = { path = "../ir", version = "=0.1.0-alpha.7" }
svod-dtype = { path = "../dtype", version = "=0.1.0-alpha.7" }
svod-device = { path = "../device", version = "=0.1.0-alpha.7" }
svod-macros = { path = "../macros", version = "=0.1.0-alpha.7" }
smallvec = { workspace = true, features = ["union"] }
sled = "0.34"
dirs = "7"
bon = "3.10"
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }

z3 = { version = "0.21", optional = true }
snafu = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "json",
], optional = true }
indexmap = "2.14.2"
rustc-hash = "2.1.3"

[features]
default = []
testing = ["dep:tracing-subscriber"]
z3 = ["dep:z3"]
proptest = ["svod-ir/proptest"]

[dev-dependencies]
proptest = "1.9.0"
svod-ir = { path = "../ir", version = "=0.1.0-alpha.7", features = [
  "proptest",
] }
test-case = "3.3.1"
