use super::*;

const SM86: CudaArch = CudaArch { major: 8, minor: 6 };

const GOLDEN_PTX: &str = "//\n// Generated by LLVM NVPTX Back-End\n//\n\n.version 8.8\n.target sm_86\n.address_size 64\n\n\
.visible .entry k(\n\t.param .u64 .ptr .align 1 k_param_0\n)\n{\n\tret;\n}\n";

#[test_case::test_case(GOLDEN_PTX, SM86, "k" => true; "golden kernel")]
#[test_case::test_case(GOLDEN_PTX, CudaArch { major: 8, minor: 9 }, "k" => false; "wrong target")]
#[test_case::test_case(GOLDEN_PTX, SM86, "other" => false; "wrong entry")]
#[test_case::test_case(GOLDEN_PTX, SM86, "" => false; "empty entry name")]
#[test_case::test_case(".target sm_86\n.visible .entry k()\n", SM86, "k" => false; "missing version")]
#[test_case::test_case(".version 8.8\n.visible .entry k()\n", SM86, "k" => false; "missing target")]
#[test_case::test_case(".version 8.8\n.target sm_86\n.func f()\n{\n}\n", SM86, "k" => false; "missing entry")]
#[test_case::test_case(".version 8.8\n.target sm_86\n.entry k(\n)\n{\n}\n", SM86, "k" => true; "bare entry")]
#[test_case::test_case(".version 8.8\n.target sm_86\n.weak .entry k(\n.param .u64 p\n)\n{\n}\n", SM86, "k" => true; "weak entry")]
#[test_case::test_case(".version 8.8\n.target sm_86\n.visible .entry kk()\n", SM86, "k" => false; "entry name is a prefix")]
#[test_case::test_case(".version 8.8\n.target sm_86, debug\n.visible .entry k()\n", SM86, "k" => true; "target with options")]
#[test_case::test_case(".version 8.8\n.target sm_86\n.extern .func (.param .b32 r) f();\n.visible .entry k()\n", SM86, "k" => false; "unresolved extern func")]
#[test_case::test_case(".version x.y\n.target sm_86\n.visible .entry k()\n", SM86, "k" => false; "malformed version")]
fn validate_ptx_cases(ptx: &str, arch: CudaArch, kernel: &str) -> bool {
    validate_ptx(ptx.as_bytes(), arch, kernel).is_ok()
}

fn ptxas_or_skip() -> Option<Ptxas> {
    let ptxas = Ptxas::discover(None);
    if ptxas.is_none() {
        eprintln!("skipping: no ptxas on this host");
    }
    ptxas
}

/// A cubin assembled by `ptxas` validates only for its own entry, and the
/// header checks catch a corrupted or foreign image.
#[test_case::test_case(|_| {}, "k", true; "ptxas cubin")]
#[test_case::test_case(|_| {}, "other", false; "missing entry")]
#[test_case::test_case(|cubin| cubin[18..20].copy_from_slice(&object::elf::EM_X86_64.to_le_bytes()), "k", false; "wrong machine")]
#[test_case::test_case(|cubin| cubin[4] = object::elf::ELFCLASS32, "k", false; "elf32")]
#[test_case::test_case(|cubin| cubin[5] = object::elf::ELFDATA2MSB, "k", false; "big endian")]
#[test_case::test_case(|cubin| cubin.truncate(200), "k", false; "truncated")]
fn validate_cubin_cases(mutate: fn(&mut Vec<u8>), entry: &str, valid: bool) {
    let Some(ptxas) = ptxas_or_skip() else { return };
    let mut cubin = ptxas.assemble(GOLDEN_PTX.as_bytes(), SM86).expect("assemble the golden kernel");
    assert!(svod_device::cuda::is_cubin(&cubin));
    mutate(&mut cubin);
    assert_eq!(svod_device::cuda::validate_cubin(&cubin, entry).is_ok(), valid);
}

#[test]
fn ptxas_reports_assembly_errors() {
    let Some(ptxas) = ptxas_or_skip() else { return };
    let error = ptxas.assemble(b"not ptx\n", SM86).expect_err("garbage must fail");
    assert!(format!("{error}").contains("ptxas"), "{error}");
    let wrong_arch = GOLDEN_PTX.replace(".target sm_86", ".target sm_90");
    let error = ptxas.assemble(wrong_arch.as_bytes(), SM86).expect_err("PTX above the requested arch must fail");
    assert!(format!("{error}").contains("ptxas"), "{error}");
    assert!(ptxas.identity().starts_with("ptxas:path="), "{}", ptxas.identity());
}

#[test]
fn ptxas_flags_name_the_standard_streams() {
    assert_eq!(ptxas_flags(SM86), ["-arch=sm_86", "-o", "/dev/stdout", "/dev/stdin"]);
}

#[test]
fn invalid_utf8_is_rejected() {
    assert!(validate_ptx(&[0xff, 0xfe, 0xfd], SM86, "k").is_err());
}

#[test]
fn ptx_flags_select_ir_input_assembly_output_and_arch() {
    let flags = ptx_flags(SM86);
    assert_eq!(&flags[..2], ["-x", "ir"]);
    assert!(flags.contains(&"-S".to_string()));
    assert!(flags.contains(&"--target=nvptx64-nvidia-cuda".to_string()));
    assert!(flags.contains(&"-march=sm_86".to_string()));
    assert!(flags.contains(&"--cuda-feature=+ptx78".to_string()));
    assert_eq!(&flags[flags.len() - 3..], ["-", "-o", "-"]);
}

/// Round-trips a tiny NVPTX kernel through clang and pins that the resulting
/// PTX validates only against the arch and entry point it was built for.
/// Without an NVPTX target, the failure must at least be a clean error.
#[test]
fn compile_smoke_sm86() {
    if !has_nvptx_target() {
        let err = compile_ir_to_ptx("; empty\n", SM86).expect_err("must fail without nvptx target");
        assert!(format!("{err}").contains("NVPTX"), "unexpected error message: {err}");
        return;
    }

    let ir = r#"; ModuleID = 'nvptx_smoke'
source_filename = "nvptx_smoke"
target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.tid.x()
declare float @llvm.exp2.f32(float)

define ptx_kernel void @nvptx_smoke(ptr noalias %buf0) #0 {
entry:
  %tid = tail call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
  %tid_ext = zext i32 %tid to i64
  %p = getelementptr inbounds float, ptr %buf0, i64 %tid_ext
  %v = load float, ptr %p
  %e = call float @llvm.exp2.f32(float %v)
  store float %e, ptr %p
  ret void
}

attributes #0 = { alwaysinline nounwind "no-trapping-math"="true" }
"#;
    let ptx = compile_ir_to_ptx(ir, SM86).expect("nvptx compile");
    let text = std::str::from_utf8(&ptx).expect("PTX is text");
    assert!(text.contains("ex2.approx.f32"), "{text}");
    assert!(text.contains("\n.version 7.8\n"), "the ISA is pinned, not the host clang's newest:\n{text}");
    validate_ptx(&ptx, SM86, "nvptx_smoke").expect("valid sm_86 PTX");
    assert!(validate_ptx(&ptx, CudaArch { major: 8, minor: 9 }, "nvptx_smoke").is_err(), "wrong arch must fail");
    assert!(validate_ptx(&ptx, SM86, "other_kernel").is_err(), "wrong kernel must fail");

    // A misspelt intrinsic is accepted by clang but lands in the PTX as an
    // external call; the validator is what catches it.
    let bogus = ir.replace("@llvm.exp2.f32", "@llvm.nvvm.lg2.approx.f32");
    let ptx = compile_ir_to_ptx(&bogus, SM86).expect("clang accepts the module");
    let err = validate_ptx(&ptx, SM86, "nvptx_smoke").expect_err("unresolved intrinsic must fail validation");
    assert!(format!("{err}").contains("unresolved"), "{err}");

    let err = compile_ir_to_ptx("this is not IR\n", SM86).expect_err("garbage must fail");
    assert!(format!("{err}").contains("nvptx"), "{err}");
}
