[package]
name = "svod-codegen"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Backend code generation for the Svod ML compiler"
readme = "README.md"

[dependencies]
svod-dtype = { path = "../dtype", version = "=0.2.0" }
svod-ir = { path = "../ir", version = "=0.2.0" }
svod-device = { path = "../device", version = "=0.2.0" }
svod-schedule = { path = "../schedule", version = "=0.2.0" }
snafu = "0.9"
tracing = "0.1"
smallvec.workspace = true

[dev-dependencies]
test-case = "3.3.1"
