[package]
name = "svod-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for the Svod ML compiler"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3", features = ["extra-traits", "full", "parsing", "visit"] }
quote = "1"
proc-macro2 = "1"
