[package]
name = "svod-onnx"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "ONNX model importer for the Svod ML compiler"
readme = "README.md"

[dependencies]
svod-tensor = { path = "../tensor", version = "=0.2.0" }
svod-ir = { path = "../ir", version = "=0.2.0" }
svod-dtype = { path = "../dtype", version = "=0.2.0" }
prost = "0.14"
snafu = "0.9"
tracing = "0.1"
smallvec = { workspace = true }
bytemuck = "1.25"
half = "2"

[build-dependencies]
prost-build = "0.14"

[dev-dependencies]
ndarray.workspace = true
svod-schedule = { path = "../schedule", version = "=0.2.0", features = [
  "testing",
] }
